name: Hello world Pipeline
on: workflow_dispatch
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Intial Step1
        run: |
         echo "welcome to github actions manoj"
         echo "these is example for multiple statementse execution"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2 setp1
        run: echo "Runing job 2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: job3 step1
        run: echo "running job 3 step 1 cmd"
