name: Hello world Pipeline
on: workflow_dispatch
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Intial Step1
        run: |
         echo "welcome to github actions manoj"
         echo "these is example for multiple statementse execution"
